### ISSUE TITLE
chat chat chat 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2022_2_WAP_APP_TEAM1#104]
## 📑 작업 사항 
채팅 UI 작업 및 구성 

## To-do
- [x] chat UI 작성 
- [x] socket 연결 
- [x] 일정화면에서 전환 설정
- [x] 일정 항공권 조회 기능 추가 

# #✔️ 기타사항
