### ISSUE TITLE
Android / Refactor 프로필 /일정 관련 작업 수정 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2022_2_WAP_APP_TEAM1#113]
## 📑 작업 사항 
소셜 로그인 / 일반 로그인 / 프로필 사진 매칭 / 일정 불러올 경우 null 처리 

## To-do
- [x] 프로필 가져와서 매핑하기 작업 수정 
- [x] 갤러리에서 사진 가져와서 서버로 전송하는 작업 수정 
- [x] 일정 불러올 때 nullable 처리해주기 

# #✔️ 기타사항
