### ISSUE TITLE
Android / Feature CI 환경 구축하기

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2022_2_WAP_APP_TEAM1#114]
## 📑 작업 사항 
ktlint 및 CI 환경 구축하기 

## To-do
- [x] android studio ktlint setup 
- [x] 현재 프로젝트에 ktlint 적용 
- [ ] ktlint hook, action 적용하기 

# #✔️ 기타사항
설레요 설레~
