### ISSUE TITLE
로그인 / 회원가입 폼 확인 및 에러메세지 출력

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2022_2_WAP_APP_TEAM1#12]
## 📑 작업 사항 
작업할 내용 설명 

## To-do
- [x] DataBinding으로 Text ViewModel로 가져오기 
- [x] Domain 계층에서 Validate Use_case 정의 
- [x] 에러일 경우 에러 메세지 출력 

# #✔️ 기타사항
에러메세지 출력할 수 있는 부분 및 기능 찾아야함.
