### ISSUE TITLE
웹 서버와 로그인/회원가입

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2022_2_WAP_APP_TEAM1#16]
## 📑 작업 사항 
웹서버와 로그인/회원가입 통신 후 세션 저장 

## To-do
- [x] Rest Api 설정
- [x] 통신 DTO 정의
- [x] token 받아와서 저장하기 

# #✔️ 기타사항
저장할 때 카카오, 네이버, 웹 서버 로그인 구분하기
