### ISSUE TITLE
프로필 편집 Screen 구현 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2022_2_WAP_APP_TEAM1#29]
## 📑 작업 사항 
갤러리 권한 받아서 사진 가져오기 및 개인정보 서버로 전달  

## To-do
- [x] 갤러리 권한 설정
- [x] 사진 가져오기 
- [x] 개인정보 서버로 전달하기 
- [x] 소셜 로그인으로 가져온 데이터 dataBinding 확인 

# #✔️ 기타사항

**Comment by jeongjaino** [comment]
image crop lib들이 다들 제정신이 아닌거 같아요

**Comment by jeongjaino** [comment]
image crop lib를 쓰기 위해서 jdk 버전을 바꿔야할 것 같네요.

**Comment by jeongjaino** [comment]
Room 어노테이션이 자바로 작성되어있어서 Kotlin의 Unit을 못알아봐서 오류가 발생했었음 하,,, 살았다.
