### ISSUE TITLE
앱 링크 및 카카오 링크 구현 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2022_2_WAP_APP_TEAM1#70]
## 📑 작업 사항 
카카오 링크 설정 및 디폴트 템플릿 제작하여 다른 유저에게 카카오링크 전송하기

## To-do
- [x] 카카오 링크 설정 
- [x] 디폴트 템플릿 제작 
- [x] 파라미터 넘겨주고 받아오기 

# #✔️ 기타사항
