### ISSUE TITLE
일정 삭제 기능 추가

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2022_2_WAP_APP_TEAM1#87]
## 📑 작업 사항 
일정 삭제 기능 추가 

## To-do
- [x] item cardView icon 추가  
- [x] adpater에 callback 함수 작성
- [x] 서버에 삭제 요청하기 
- [x] 새로 리스트 받아와 업데이트하기 

# #✔️ 기타사항
