### ISSUE TITLE
일정 장소 전체 지도에 표시하기

### ISSUE THREAD

**Issue by SeongHoonC** [pknu-wap/2022_2_WAP_APP_TEAM1#91]
## 📑 작업할 내용 설명 
recylerView item 중 장소 만 map에 marker로 표시하고 장소 사이 거리 계산

## To-do
- [x] 아이템 중에서 장소만 가져오기
- [x] 장소 이름과 좌표를 이용하여 지도에 마커 추가하기
- [ ] 각 장소 사이 거리 계산하기
- [ ] 거리를 화면에 표시하기
- [x] 장소 클릭 시 지도 보여주기

# #✔️ 기타사항

**Comment by jeongjaino** [comment]
구글 맵은 점선이 되고,,, 카카오맵은 점선이 안되고,,, 후욱 후욱 두께도 변경이 안되고,, 후욱후욱,,,

**Comment by jeongjaino** [comment]
좌표간 거리 계산은 추후의 일정으로 
- 어댑터 아이템간 연산 작업 및 거리를 어디다 배치해야 할지 미정이라 추후에 수정
