### ISSUE TITLE
장소 기능 추가

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2022_2_WAP_APP_TEAM1#96]
## 📑 작업 사항 
사용자가 선택한 장소 일정에 추가하기

## To-do
- [x] 선택한 장소 데이터 받아오기 
- [x] 장소 추가 API 호출 
- [x] 새로운 리스트 받아오기

# #✔️ 기타사항
